#!/bin/sh
echo "creating new disk..."
eval "hdiutil create -size 8g -fs 'Case-sensitive Journaled HFS+' -volname linux-kernel ~/Documents/linux.dmg"
echo "mounting the disk..."
eval "hdiutil attach ~/Documents/linux.dmg"
eval "cp ./run_in_vm.sh /Volumes/linux-kernel"
eval "cp ./Vagrantfile /Volumes/linux-kernel"
eval "cp ./Vagrantfile2 /Volumes/linux-kernel"
eval "cd /Volumes/linux-kernel"
echo "Kernel Download start"
eval "git clone --bare https://github.com/torvalds/linux.git"
echo "Kernel Download end"

echo "changing directory to linux.git"
eval "cd linux.git"
eval "git worktree add ../linux master"
echo "Kernel-labs download start"
eval "git remote add kernel-labs https://github.com/linux-kernel-labs/linux.git"
eval "git fetch kernel-labs"
eval "git branch kernel-labs kernel-labs/master"
echo "branched kernel-labs/master"
eval "git worktree add ../kernel-labs kernel-labs"
echo "constructing vitrual machine..."
eval "vagrant up"
eval "rm Vagrantfile"
eval "cp Vagrantfile2 Vagrantfile"
eval "vagrant reload"
eval "cp "
echo "finished script."
echo "What you need to do next.."
echo "1. run 'vagrant ssh'"
echo "2. 'cp /vagrant/'"
