#!/bin/sh
echo "===Kernel Download start==="
eval "git clone --bare https://github.com/torvalds/linux.git"
echo "===Kernel Download end==="
echo "===changing directory to linux.git==="
eval "cd linux.git"
eval "git worktree add ../linux master"
echo "===Kernel-labs download start==="
eval "git remote add kernel-labs https://github.com/linux-kernel-labs/linux.git"
eval "git fetch kernel-labs"
eval "git branch kernel-labs kernel-labs/master"
echo "branched kernel-labs/master"
eval "git worktree add ../kernel-labs kernel-labs"
echo "===Finished setting==="
