#!/bin/sh
echo "changing folder to home directory"
eval "cd ~"
echo "making filesystem ext4 to /dev/sdb"
eval "sudo mkfs -t ext4 /dev/sdb"
echo "mkdir linux-kernel"
eval "mkdir ~/linux-kernel"
echo "mount to /dev/sdb to linux-kernel"
eval "sudo mount -t ext4 /dev/sdb ~/linux-kernel"
eval "sudo chown 744 vagrant:vagrant ~/linux-kernel"
eval "cd ~/linux-kernel"
echo "copy /vagrant/kernel-labs to here"
eval "cp -r /vagrant/kernel-labs ."
echo "Done provisioning. Next up..."
echo "Go to linux kernel web and start!"
echo "[Some tips before going...]"
echo "you might want to make clean tools/labs before make boot..."
